services:
  - type: web
    name: shopping-site
    env: python
    branch: master
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn shopping_site.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: .onrender.com
